// flow-typed signature: 2c22c0482d830f3817b0b5e3ed9dcd14
// flow-typed version: <<STUB>>/relay-runtime_v^5.0.0/flow_v0.111.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'relay-runtime'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'relay-runtime' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'relay-runtime/lib/handlers/connection/RelayConnectionHandler' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib/handlers/connection/RelayConnectionInterface' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib/handlers/RelayDefaultHandlerProvider' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib/handlers/RelayDefaultMissingFieldHandlers' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib/mutations/applyOptimisticMutation' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib/mutations/commitLocalUpdate' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib/mutations/commitMutation' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib/mutations/RelayDeclarativeMutationConfig' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib/mutations/RelayRecordProxy' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib/mutations/RelayRecordSourceMutator' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib/mutations/RelayRecordSourceProxy' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib/mutations/RelayRecordSourceSelectorProxy' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib/mutations/validateMutation' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib/network/ConvertToExecuteFunction' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib/network/RelayNetwork' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib/network/RelayNetworkTypes' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib/network/RelayObservable' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib/network/RelayQueryResponseCache' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib/query/fetchQuery' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib/query/fetchQueryInternal' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib/query/RelayModernGraphQLTag' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib/store/ClientID' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib/store/cloneRelayHandleSourceField' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib/store/createFragmentSpecResolver' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib/store/createRelayContext' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib/store/DataChecker' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib/store/defaultGetDataID' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib/store/hasOverlappingIDs' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib/store/isRelayModernEnvironment' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib/store/normalizeRelayPayload' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib/store/readInlineData' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib/store/RelayConcreteVariables' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib/store/RelayConnection' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib/store/RelayConnectionResolver' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib/store/RelayModernEnvironment' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib/store/RelayModernFragmentSpecResolver' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib/store/RelayModernOperationDescriptor' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib/store/RelayModernQueryExecutor' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib/store/RelayModernRecord' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib/store/RelayModernSelector' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib/store/RelayModernStore' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib/store/RelayOperationTracker' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib/store/RelayOptimisticRecordSource' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib/store/RelayPublishQueue' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib/store/RelayReader' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib/store/RelayRecordSource' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib/store/RelayRecordSourceMapImpl' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib/store/RelayRecordSourceObjectImpl' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib/store/RelayRecordState' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib/store/RelayReferenceMarker' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib/store/RelayResponseNormalizer' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib/store/RelayStoreTypes' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib/store/RelayStoreUtils' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib/store/StoreInspector' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib/store/ViewerPattern' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib/subscription/requestSubscription' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib/util/deepFreeze' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib/util/generateID' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib/util/getFragmentIdentifier' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib/util/getFragmentSpecIdentifier' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib/util/getRelayHandleKey' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib/util/getRequestIdentifier' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib/util/isPromise' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib/util/isScalarAndEqual' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib/util/NormalizationNode' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib/util/ReaderNode' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib/util/recycleNodesInto' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib/util/RelayConcreteNode' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib/util/RelayDefaultHandleKey' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib/util/RelayError' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib/util/RelayFeatureFlags' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib/util/RelayProfiler' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib/util/RelayReplaySubject' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib/util/RelayRuntimeTypes' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib/util/resolveImmediate' {
  declare module.exports: any;
}

declare module 'relay-runtime/lib/util/stableCopy' {
  declare module.exports: any;
}

declare module 'relay-runtime/relay-runtime' {
  declare module.exports: any;
}

declare module 'relay-runtime/relay-runtime.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'relay-runtime/index' {
  declare module.exports: $Exports<'relay-runtime'>;
}
declare module 'relay-runtime/index.js' {
  declare module.exports: $Exports<'relay-runtime'>;
}
declare module 'relay-runtime/lib/handlers/connection/RelayConnectionHandler.js' {
  declare module.exports: $Exports<'relay-runtime/lib/handlers/connection/RelayConnectionHandler'>;
}
declare module 'relay-runtime/lib/handlers/connection/RelayConnectionInterface.js' {
  declare module.exports: $Exports<'relay-runtime/lib/handlers/connection/RelayConnectionInterface'>;
}
declare module 'relay-runtime/lib/handlers/RelayDefaultHandlerProvider.js' {
  declare module.exports: $Exports<'relay-runtime/lib/handlers/RelayDefaultHandlerProvider'>;
}
declare module 'relay-runtime/lib/handlers/RelayDefaultMissingFieldHandlers.js' {
  declare module.exports: $Exports<'relay-runtime/lib/handlers/RelayDefaultMissingFieldHandlers'>;
}
declare module 'relay-runtime/lib/index' {
  declare module.exports: $Exports<'relay-runtime/lib'>;
}
declare module 'relay-runtime/lib/index.js' {
  declare module.exports: $Exports<'relay-runtime/lib'>;
}
declare module 'relay-runtime/lib/mutations/applyOptimisticMutation.js' {
  declare module.exports: $Exports<'relay-runtime/lib/mutations/applyOptimisticMutation'>;
}
declare module 'relay-runtime/lib/mutations/commitLocalUpdate.js' {
  declare module.exports: $Exports<'relay-runtime/lib/mutations/commitLocalUpdate'>;
}
declare module 'relay-runtime/lib/mutations/commitMutation.js' {
  declare module.exports: $Exports<'relay-runtime/lib/mutations/commitMutation'>;
}
declare module 'relay-runtime/lib/mutations/RelayDeclarativeMutationConfig.js' {
  declare module.exports: $Exports<'relay-runtime/lib/mutations/RelayDeclarativeMutationConfig'>;
}
declare module 'relay-runtime/lib/mutations/RelayRecordProxy.js' {
  declare module.exports: $Exports<'relay-runtime/lib/mutations/RelayRecordProxy'>;
}
declare module 'relay-runtime/lib/mutations/RelayRecordSourceMutator.js' {
  declare module.exports: $Exports<'relay-runtime/lib/mutations/RelayRecordSourceMutator'>;
}
declare module 'relay-runtime/lib/mutations/RelayRecordSourceProxy.js' {
  declare module.exports: $Exports<'relay-runtime/lib/mutations/RelayRecordSourceProxy'>;
}
declare module 'relay-runtime/lib/mutations/RelayRecordSourceSelectorProxy.js' {
  declare module.exports: $Exports<'relay-runtime/lib/mutations/RelayRecordSourceSelectorProxy'>;
}
declare module 'relay-runtime/lib/mutations/validateMutation.js' {
  declare module.exports: $Exports<'relay-runtime/lib/mutations/validateMutation'>;
}
declare module 'relay-runtime/lib/network/ConvertToExecuteFunction.js' {
  declare module.exports: $Exports<'relay-runtime/lib/network/ConvertToExecuteFunction'>;
}
declare module 'relay-runtime/lib/network/RelayNetwork.js' {
  declare module.exports: $Exports<'relay-runtime/lib/network/RelayNetwork'>;
}
declare module 'relay-runtime/lib/network/RelayNetworkTypes.js' {
  declare module.exports: $Exports<'relay-runtime/lib/network/RelayNetworkTypes'>;
}
declare module 'relay-runtime/lib/network/RelayObservable.js' {
  declare module.exports: $Exports<'relay-runtime/lib/network/RelayObservable'>;
}
declare module 'relay-runtime/lib/network/RelayQueryResponseCache.js' {
  declare module.exports: $Exports<'relay-runtime/lib/network/RelayQueryResponseCache'>;
}
declare module 'relay-runtime/lib/query/fetchQuery.js' {
  declare module.exports: $Exports<'relay-runtime/lib/query/fetchQuery'>;
}
declare module 'relay-runtime/lib/query/fetchQueryInternal.js' {
  declare module.exports: $Exports<'relay-runtime/lib/query/fetchQueryInternal'>;
}
declare module 'relay-runtime/lib/query/RelayModernGraphQLTag.js' {
  declare module.exports: $Exports<'relay-runtime/lib/query/RelayModernGraphQLTag'>;
}
declare module 'relay-runtime/lib/store/ClientID.js' {
  declare module.exports: $Exports<'relay-runtime/lib/store/ClientID'>;
}
declare module 'relay-runtime/lib/store/cloneRelayHandleSourceField.js' {
  declare module.exports: $Exports<'relay-runtime/lib/store/cloneRelayHandleSourceField'>;
}
declare module 'relay-runtime/lib/store/createFragmentSpecResolver.js' {
  declare module.exports: $Exports<'relay-runtime/lib/store/createFragmentSpecResolver'>;
}
declare module 'relay-runtime/lib/store/createRelayContext.js' {
  declare module.exports: $Exports<'relay-runtime/lib/store/createRelayContext'>;
}
declare module 'relay-runtime/lib/store/DataChecker.js' {
  declare module.exports: $Exports<'relay-runtime/lib/store/DataChecker'>;
}
declare module 'relay-runtime/lib/store/defaultGetDataID.js' {
  declare module.exports: $Exports<'relay-runtime/lib/store/defaultGetDataID'>;
}
declare module 'relay-runtime/lib/store/hasOverlappingIDs.js' {
  declare module.exports: $Exports<'relay-runtime/lib/store/hasOverlappingIDs'>;
}
declare module 'relay-runtime/lib/store/isRelayModernEnvironment.js' {
  declare module.exports: $Exports<'relay-runtime/lib/store/isRelayModernEnvironment'>;
}
declare module 'relay-runtime/lib/store/normalizeRelayPayload.js' {
  declare module.exports: $Exports<'relay-runtime/lib/store/normalizeRelayPayload'>;
}
declare module 'relay-runtime/lib/store/readInlineData.js' {
  declare module.exports: $Exports<'relay-runtime/lib/store/readInlineData'>;
}
declare module 'relay-runtime/lib/store/RelayConcreteVariables.js' {
  declare module.exports: $Exports<'relay-runtime/lib/store/RelayConcreteVariables'>;
}
declare module 'relay-runtime/lib/store/RelayConnection.js' {
  declare module.exports: $Exports<'relay-runtime/lib/store/RelayConnection'>;
}
declare module 'relay-runtime/lib/store/RelayConnectionResolver.js' {
  declare module.exports: $Exports<'relay-runtime/lib/store/RelayConnectionResolver'>;
}
declare module 'relay-runtime/lib/store/RelayModernEnvironment.js' {
  declare module.exports: $Exports<'relay-runtime/lib/store/RelayModernEnvironment'>;
}
declare module 'relay-runtime/lib/store/RelayModernFragmentSpecResolver.js' {
  declare module.exports: $Exports<'relay-runtime/lib/store/RelayModernFragmentSpecResolver'>;
}
declare module 'relay-runtime/lib/store/RelayModernOperationDescriptor.js' {
  declare module.exports: $Exports<'relay-runtime/lib/store/RelayModernOperationDescriptor'>;
}
declare module 'relay-runtime/lib/store/RelayModernQueryExecutor.js' {
  declare module.exports: $Exports<'relay-runtime/lib/store/RelayModernQueryExecutor'>;
}
declare module 'relay-runtime/lib/store/RelayModernRecord.js' {
  declare module.exports: $Exports<'relay-runtime/lib/store/RelayModernRecord'>;
}
declare module 'relay-runtime/lib/store/RelayModernSelector.js' {
  declare module.exports: $Exports<'relay-runtime/lib/store/RelayModernSelector'>;
}
declare module 'relay-runtime/lib/store/RelayModernStore.js' {
  declare module.exports: $Exports<'relay-runtime/lib/store/RelayModernStore'>;
}
declare module 'relay-runtime/lib/store/RelayOperationTracker.js' {
  declare module.exports: $Exports<'relay-runtime/lib/store/RelayOperationTracker'>;
}
declare module 'relay-runtime/lib/store/RelayOptimisticRecordSource.js' {
  declare module.exports: $Exports<'relay-runtime/lib/store/RelayOptimisticRecordSource'>;
}
declare module 'relay-runtime/lib/store/RelayPublishQueue.js' {
  declare module.exports: $Exports<'relay-runtime/lib/store/RelayPublishQueue'>;
}
declare module 'relay-runtime/lib/store/RelayReader.js' {
  declare module.exports: $Exports<'relay-runtime/lib/store/RelayReader'>;
}
declare module 'relay-runtime/lib/store/RelayRecordSource.js' {
  declare module.exports: $Exports<'relay-runtime/lib/store/RelayRecordSource'>;
}
declare module 'relay-runtime/lib/store/RelayRecordSourceMapImpl.js' {
  declare module.exports: $Exports<'relay-runtime/lib/store/RelayRecordSourceMapImpl'>;
}
declare module 'relay-runtime/lib/store/RelayRecordSourceObjectImpl.js' {
  declare module.exports: $Exports<'relay-runtime/lib/store/RelayRecordSourceObjectImpl'>;
}
declare module 'relay-runtime/lib/store/RelayRecordState.js' {
  declare module.exports: $Exports<'relay-runtime/lib/store/RelayRecordState'>;
}
declare module 'relay-runtime/lib/store/RelayReferenceMarker.js' {
  declare module.exports: $Exports<'relay-runtime/lib/store/RelayReferenceMarker'>;
}
declare module 'relay-runtime/lib/store/RelayResponseNormalizer.js' {
  declare module.exports: $Exports<'relay-runtime/lib/store/RelayResponseNormalizer'>;
}
declare module 'relay-runtime/lib/store/RelayStoreTypes.js' {
  declare module.exports: $Exports<'relay-runtime/lib/store/RelayStoreTypes'>;
}
declare module 'relay-runtime/lib/store/RelayStoreUtils.js' {
  declare module.exports: $Exports<'relay-runtime/lib/store/RelayStoreUtils'>;
}
declare module 'relay-runtime/lib/store/StoreInspector.js' {
  declare module.exports: $Exports<'relay-runtime/lib/store/StoreInspector'>;
}
declare module 'relay-runtime/lib/store/ViewerPattern.js' {
  declare module.exports: $Exports<'relay-runtime/lib/store/ViewerPattern'>;
}
declare module 'relay-runtime/lib/subscription/requestSubscription.js' {
  declare module.exports: $Exports<'relay-runtime/lib/subscription/requestSubscription'>;
}
declare module 'relay-runtime/lib/util/deepFreeze.js' {
  declare module.exports: $Exports<'relay-runtime/lib/util/deepFreeze'>;
}
declare module 'relay-runtime/lib/util/generateID.js' {
  declare module.exports: $Exports<'relay-runtime/lib/util/generateID'>;
}
declare module 'relay-runtime/lib/util/getFragmentIdentifier.js' {
  declare module.exports: $Exports<'relay-runtime/lib/util/getFragmentIdentifier'>;
}
declare module 'relay-runtime/lib/util/getFragmentSpecIdentifier.js' {
  declare module.exports: $Exports<'relay-runtime/lib/util/getFragmentSpecIdentifier'>;
}
declare module 'relay-runtime/lib/util/getRelayHandleKey.js' {
  declare module.exports: $Exports<'relay-runtime/lib/util/getRelayHandleKey'>;
}
declare module 'relay-runtime/lib/util/getRequestIdentifier.js' {
  declare module.exports: $Exports<'relay-runtime/lib/util/getRequestIdentifier'>;
}
declare module 'relay-runtime/lib/util/isPromise.js' {
  declare module.exports: $Exports<'relay-runtime/lib/util/isPromise'>;
}
declare module 'relay-runtime/lib/util/isScalarAndEqual.js' {
  declare module.exports: $Exports<'relay-runtime/lib/util/isScalarAndEqual'>;
}
declare module 'relay-runtime/lib/util/NormalizationNode.js' {
  declare module.exports: $Exports<'relay-runtime/lib/util/NormalizationNode'>;
}
declare module 'relay-runtime/lib/util/ReaderNode.js' {
  declare module.exports: $Exports<'relay-runtime/lib/util/ReaderNode'>;
}
declare module 'relay-runtime/lib/util/recycleNodesInto.js' {
  declare module.exports: $Exports<'relay-runtime/lib/util/recycleNodesInto'>;
}
declare module 'relay-runtime/lib/util/RelayConcreteNode.js' {
  declare module.exports: $Exports<'relay-runtime/lib/util/RelayConcreteNode'>;
}
declare module 'relay-runtime/lib/util/RelayDefaultHandleKey.js' {
  declare module.exports: $Exports<'relay-runtime/lib/util/RelayDefaultHandleKey'>;
}
declare module 'relay-runtime/lib/util/RelayError.js' {
  declare module.exports: $Exports<'relay-runtime/lib/util/RelayError'>;
}
declare module 'relay-runtime/lib/util/RelayFeatureFlags.js' {
  declare module.exports: $Exports<'relay-runtime/lib/util/RelayFeatureFlags'>;
}
declare module 'relay-runtime/lib/util/RelayProfiler.js' {
  declare module.exports: $Exports<'relay-runtime/lib/util/RelayProfiler'>;
}
declare module 'relay-runtime/lib/util/RelayReplaySubject.js' {
  declare module.exports: $Exports<'relay-runtime/lib/util/RelayReplaySubject'>;
}
declare module 'relay-runtime/lib/util/RelayRuntimeTypes.js' {
  declare module.exports: $Exports<'relay-runtime/lib/util/RelayRuntimeTypes'>;
}
declare module 'relay-runtime/lib/util/resolveImmediate.js' {
  declare module.exports: $Exports<'relay-runtime/lib/util/resolveImmediate'>;
}
declare module 'relay-runtime/lib/util/stableCopy.js' {
  declare module.exports: $Exports<'relay-runtime/lib/util/stableCopy'>;
}
declare module 'relay-runtime/relay-runtime.js' {
  declare module.exports: $Exports<'relay-runtime/relay-runtime'>;
}
declare module 'relay-runtime/relay-runtime.min.js' {
  declare module.exports: $Exports<'relay-runtime/relay-runtime.min'>;
}
